# Version of the application
version: 0.8.0
# Name of the application
name: tellery
# A short description of the application
description: Docker Compose File for Tellery
# List of application maintainers with name and email for each
maintainers:
  - name: tellery authors
    email: contact@tellery.io
